import "./globals.css";
import { ThemeProvider } from "./ThemeProvider";

// NB : on n'utilise PAS next/font/google (Geist/Geist_Mono). Ces polices étaient
// un résidu du template create-next-app, jamais référencées dans le CSS (le body
// est rendu en Arial/Helvetica via globals.css). Les charger imposait un
// téléchargement réseau de Google Fonts AU MOMENT DU BUILD (`npm run build`), ce
// qui faisait échouer la construction de l'image dès que fonts.googleapis.com
// n'était pas joignable. Suppression → build hors-ligne possible, rendu inchangé.

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = localStorage.getItem('osirion-theme') || 'system';
                const isDark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
                if (isDark) {
                  document.documentElement.classList.add('dark');
                  document.documentElement.style.colorScheme = 'dark';
                } else {
                  document.documentElement.classList.remove('dark');
                  document.documentElement.style.colorScheme = 'light';
                }
              } catch (e) {}
            `,
          }}
        />
      </head>
      <body className="antialiased">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
